### ISSUE TITLE
카톡 로그인 했을때 displayName 수정 안됨.

### ISSUE THREAD

**Issue by SeongwoonHong** [dam-so/damso#73]
<img width="988" alt="screen shot 2018-01-19 at 8 01 05 pm" src="https://user-images.githubusercontent.com/19713918/35178097-7f4e7c3a-fd53-11e7-95c4-02b75229717f.png">

**Comment by lyndonoc** [comment]
can't replicate this on my end, need more info

**Comment by SeongwoonHong** [comment]
closed.
