### ISSUE TITLE
implement continuous integration using travis ci

### ISSUE THREAD

**Issue by lyndonoc** [dam-so/damso#84]
ideally, pushing or merging to the master branch should trigger travis ci, which will hopefully do the following.

- run the tests for both client & server
- build the client side react app into /server/public folder
- push the server directory to heroku, which will host the app.

**Comment by lyndonoc** [comment]
this is working at this moment, but .travis.yml needs to be edited for faster build & testing

**Comment by SeongwoonHong** [comment]
done.
